spring:
  datasource:
    url: jdbc:h2:file:/Users/jicircle/test0207/testdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

jwt:
  secret: my-secret-key-my-secret-key-my-secret-key