spring:
  config:
    import: optional:application-secret.yml
  profiles:
    active: local #TODO 나중에 deployment로 바꾸기
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100


# Swagger UI 경로: http://localhost:8080/swagger-ui.html
springdoc:
  default-consume-media-type: application/json
  default-produce-media-type: application/json
  # Pageable 관련 오류 방지
  show-actuator: true